version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      dockerfile: src/dashboard/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
